name: Build APK

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    name: Building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install

      - name: Run test
        run: |
          yarn test

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd packages/mobile/android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd packages/mobile/android && ./gradlew assembleRelease --no-daemon

      # To add new GitHub Action secrets, open your Github project home page 
      # Project Setting > Secrets > Actions > new repository secret
      - name: Sign App APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: packages/mobile/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_SIGNING_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}

      # This apk can be downloaded on the action page, not release page
      - name: Upload Artifact (APK file)
        uses: actions/upload-artifact@v3
        with:
          name: Signed App Bundle # will be the file name
          path: packages/mobile/android/app/build/outputs/apk/release/app-release.apk